In [1]:
import numpy as np

basic array creation

In [2]:
arr =np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5,"hello"]

In [5]:
a

[1, 2, 3.5, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [7]:
 arr = np.zeros([4,4])

In [8]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr = np.ones([3,3])

In [11]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr = np.linspace(1,2,10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

# random generator function 

In [13]:
np.random.rand(10)

array([0.62752638, 0.14357684, 0.59279512, 0.37259231, 0.12363786,
       0.86800933, 0.12711522, 0.12889136, 0.39749936, 0.69827199])

In [14]:
np.random.randn(10)

array([ 0.58711145,  0.31553368,  0.23672549, -0.44749778, -0.27461432,
        0.0451063 ,  0.19464574,  0.3439916 , -0.9096829 , -0.68175832])

In [15]:
np.random.randint(12,60,10)

array([34, 43, 47, 34, 28, 26, 25, 17, 32, 12], dtype=int32)

In [16]:
arr = np.arange(11,21)

In [17]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
arr[7]

np.int64(18)

In [19]:
arr[1:5]

array([12, 13, 14, 15])

In [20]:
err = np.arange(1,31).reshape(6,5)

In [21]:
err

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
slice = err[2:4,2:4] 
slice

array([[13, 14],
       [18, 19]])

In [23]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Array operations

In [26]:
import numpy as np


In [27]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [28]:
arr = a1+a2

In [29]:
arr

array([ 7,  9, 11, 13, 15])

In [30]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [31]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [32]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [33]:
a1//a2

array([0, 0, 0, 0, 0])

In [34]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# brodcasting

In [35]:
l = [10,20,30,40]

In [36]:
arr = np.array(l)

In [37]:
arr -10

array([ 0, 10, 20, 30])

# Deep and shallow copy

# Exercise


# Valid Sudoku

In [38]:
import numpy as np

In [39]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [40]:
np.sum(s, axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [41]:
np.sum(s, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [42]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n= s[i:i+3,j:j+3]
        print(n)

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [43]:
print(n.sum())

45


# General Questions

In [44]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [45]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [46]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [47]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [48]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [49]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [50]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [51]:
#Find how many students are younger than 19.
len(data[data[:,0] <19])

3

In [52]:
#Calculate the average marks in each subject (column-wise mean)
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [53]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [54]:
#Replace all Science marks < 75 with 0.
data[:,2] [data[:,2]<75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])